apiVersion: v1
kind: Service
metadata:
  name: {{ include "clusterino.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "clusterino.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "clusterino.selectorLabels" . | nindent 4 }}
