apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster.fullname" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
    app: node
spec:
  type: ClusterIP
  clusterIP: None #headless service definition
  ports:
    - port: {{ .Values.nodeRpcPort}}
      targetPort: {{ .Values.nodeRpcPort}}
  selector:
    {{- include "cluster.selectorLabels" . | nindent 4 }}
    app: node
